---
- name: Install Docker and Docker Compose
  hosts: all
  become: true

  tasks:
    - name: Install required packages
      package:
        name: ["apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common"]
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Docker and Docker Compose dependencies
      package:
        name: ["yum-utils", "device-mapper-persistent-data", "lvm2"]
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Add Docker repository
      yum_repository:
        baseurl: https://download.docker.com/linux/{{ ansible_distribution_major_version }}/$basearch/stable
        gpgcheck: yes
        enabled: yes
        gpgkey: https://download.docker.com/linux/{{ ansible_distribution_major_version }}/gpg
        name: Docker CE Stable - $basearch
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install Docker and Docker Compose
      package:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
        state: present